---
title: "RWorksheet_Arcenas#4b"
author: "Edora Frances Anne V Arcenas"
date: "2023-11-08"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}

#a
Vector_A <- c(1,2,3,4,5)

MatrixA <- matrix(0, nrow = 5, ncol = 5)

MatrixA[1,] <- Vector_A

print(MatrixA)

```

```{r}
#2
RowsEme <- 5

for (i in 1:RowsEme) {
  for (j in 1:i) {
    cat("*")
  }
  cat("\n")
}
```

```{r}
#3
input <- as.integer(readline(prompt = "Enter a number: "))

prev <- 0
curr <- 1

print(curr)

repeat {
  next_num <- prev + curr
  if (next_num > 500) {
    break
  }
  print(next_num)
  prev <- curr
  curr <- next_num
}
```

```{r}
ImportedDataSet <- read.csv(file =  "/cloud/project/worksheet#4/ShoeSizeHeightGender.csv", header = TRUE, sep = ",")

head(ImportedDataSet, 6)

```

```{r}
data("iris")
iris

str(iris)

MeanPetalObject <-
  mean(iris$Sepal.Length)
  mean(iris$Sepal.Width)
  mean(iris$Petal.Length)
  mean(iris$Petal.Width)
  
  IrisSpecies <- table(iris$Species)
pie(IrisSpecies, labels = names(IrisSpecies), main = "Iris Species Distribution", col = rainbow(length(IrisSpecies)))
legend("topright", legend = names(IrisSpecies), fill = rainbow(length(IrisSpecies)))

setosa <- subset(iris, Species == "setosa")
versicolor <- subset(iris, Species == "versicolor")
virginica <- subset(iris, Species == "virginica")

tail(setosa, 6)
tail(versicolor, 6)
tail(virginica, 6)

iris$Species <- as.factor(iris$Species)

plot(iris$Sepal.Length, iris$Sepal.Width, col = iris$Species, pch = 19,
     xlab = "Sepal Length", ylab = "Sepal Width",
     main = "Iris Dataset", sub = "Sepal width and length")
legend("topright", legend = levels(iris$Species), col = 1:length(levels(iris$Species)), pch = 19)
```

