---
title: "Worksheet 6"
author: "Edora Frances Anne V Arcenas"
date: "2023-12-19"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}

Stud_Score <- data.frame(
  Student = c(1:10),
  Pre_test = c(55,54,47,57,51,61,57,54,63,58),
  Post_test = c(61,60,56,63,56,63,59,56,62,61)
)
Stud_Score

library(pastecs)
library(Hmisc)

pastecs_Stats <- stat.desc(Stud_Score)
pastecs_Stats

hmisc_Stats <- Hmisc::describe(Stud_Score[,c("Pre_test","Post_test")])
hmisc_Stats

```

```{r}

library(dplyr)

LevelFert <- c(10,10,10, 20,20,50,10,20,10,50,20,50,20,10)
orderedLvlFertilizer <- factor(LevelFert, levels = unique(LevelFert))

summary_Fertilizer <- summary(orderedLvlFertilizer)
summary_Fertilizer

```

```{r}

LevelExer <- c("n", "l", "n", "n", "l", "l", "n", "n", "i", "l")
factoredLvlExercise <- factor(LevelExer, levels = c("n","l","i"))

summary_Exercise <- summary(factoredLvlExercise)
summary_Exercise

```

```{r}

States <- c("tas", "sa", "qld", "nsw", "nsw", "nt", "wa", "wa", "qld", "vic", "nsw", "vic", "qld", "qld", "sa", "tas", "sa", "nt", "wa", "vic", "qld", "nsw", "nsw", "wa", "sa", "act", "nsw", "vic", "vic", "act")

factored_State <- factor(States)
factored_State

summary_States <- summary(factored_State)
summary_States

# The outcome will be a factor that corresponds to the distinct values in the initial character vector. Each tier signifies a particular state or region, and they are arranged in alphabetical sequence.

```

```{r}

incomes <- c(60, 49, 40, 61, 64, 60, 59, 54,
62, 69, 70, 42, 56, 61, 61, 61, 58, 51, 48,
65, 49, 49, 41, 48, 52, 46, 59, 46, 58, 43)

mean_Incomes <- tapply(incomes, factored_State, mean)
mean_Incomes

```

```{r}

std_Error <- function(x) sqrt(var(x)/length(x))
incster <- tapply(incomes, States, std_Error)

standard_Error <- tapply(incomes, factored_State, std_Error)
standard_Error

```

```{r}
library(titanic)

data("titanic_train")
titanic_data <- titanic_train

str(titanic_data)

survived <- subset(titanic_data, Survived == 1)
survived

dead <- subset(titanic_data, Survived == 0)
dead

head(survived)
head(dead)

```

```{r}

library(readr)
library(pastecs)
library(Hmisc)

breast_Cancer <- read.csv("breastcancer_wisconsin.csv")

breast_CancerStats <- stat.desc(breast_Cancer)
breast_CancerStats

clump_thickness_SEmean <- breast_CancerStats["SE.mean", "clump_thickness"]
clump_thickness_SEmean

marginal_adhesion_coefVar <- breast_CancerStats["coef.var", "marginal_adhesion"]
marginal_adhesion_coefVar

bare_nucleoli_null <- breast_CancerStats["nbr.null", "bare_nucleoli"]
bare_nucleoli_null

bland_chromatin_mean <- breast_CancerStats["mean", "bland_chromatin"]
bland_chromatin_mean

bland_chromatin_std_dev <- breast_CancerStats["std.dev", "bland_chromatin"]
bland_chromatin_std_dev

shape_uniformity_CImean <- breast_CancerStats["CI.mean", "shape_uniformity"]
shape_uniformity_CImean
```


```{r}
num_attributes <- ncol(breast_Cancer)
num_attributes
```

```{r}

# Assuming class 4 is malignant

percentage_malignant <- (sum(breast_Cancer$class == 4) / nrow(breast_Cancer)) * 100
paste0("Percentage of Respondents who are Malignant: ", percentage_malignant,"%")

```

```{r}
library("AppliedPredictiveModeling")
library("readxl")
abalone <-read_excel("abalone.xlsx")
head(abalone)
summary(abalone)
head(abalone)
summary(abalone)
```